jobs:
  include:
  - name: “Ruby language basic test”
    language: ruby
    script:
      - ruby ./source/ruby_hello.rb
  - name: “Python language basic test”
    language: python
    script:
      - python source/python_hello.py
