jobs:
  include:
#   - name: “Ruby language basic test”
#     language: ruby
#     ruby:
#       - 3.0.4
#     script:
#       - ruby ./source/ruby_hello.rb
#   - name: “Python language basic test”
#     language: python
#     python:
#        - 3.8.13
#     script:
#       - python source/python_hello.py
  - name: “Perl language basic test”
    language: perl
    perl:
       - 5.34.1
    script:
      - perl ./source/python_hello.py
  - name: “erlang language basic test”
    language: erlang
    script:
      - echo "Erlang language installed !!"
      - erlc hello_world.erl

